from django.urls import path
from . import views
from . import lead_views
from . import lead_report_views


urlpatterns = [
    path("", views.landing_home, name="landing_home"),
    path("signup/", views.public_signup, name="public_signup"),
    path("trial-expired/", views.trial_expired, name="trial_expired"),
    path("pending-approval/", views.pending_approval, name="pending_approval"),
    path(
        "followup/signup-approvals/",
        views.followup_signup_approvals,
        name="followup_signup_approvals",
    ),
    path("login/", views.login_view, name="login"),
    path("home/", views.home, name="home"),
    path("logout/", views.logout_view, name="logout"),
    path("account/profile/", views.manage_account, name="manage_account"),
    path("customers/", views.customer_list, name="customer_list"),
    path("customers/add/", views.register_customer, name="register_customer"),
    path("customers/<int:cust_id>/edit/", views.edit_customer, name="edit_customer"),
    path("leads/", lead_views.lead_list, name="lead_list"),
    path("leads/add/", lead_views.lead_add, name="lead_add"),
    path("leads/check-booking/", lead_views.lead_check_booking, name="lead_check_booking"),
    path("leads/reports/", lead_report_views.lead_reports_hub, name="lead_reports_hub"),
    path("leads/reports/summary/", lead_report_views.lead_summary_report, name="lead_summary_report"),
    path("leads/reports/status/", lead_report_views.lead_status_report, name="lead_status_report"),
    path("leads/reports/source/", lead_report_views.lead_source_report, name="lead_source_report"),
    path("leads/reports/project/", lead_report_views.lead_project_report, name="lead_project_report"),
    path("leads/reports/staff/", lead_report_views.lead_staff_report, name="lead_staff_report"),
    path("leads/reports/conversion/", lead_report_views.lead_conversion_report, name="lead_conversion_report"),
    path("leads/reports/follow-up/", lead_report_views.lead_followup_report, name="lead_followup_report"),
    path("leads/reports/activity/", lead_report_views.lead_activity_report, name="lead_activity_report"),
    path("leads/<int:lead_id>/", lead_views.lead_detail, name="lead_detail"),
    path("leads/<int:lead_id>/edit/", lead_views.lead_edit, name="lead_edit"),
    path("leads/<int:lead_id>/confirm/", lead_views.lead_confirm, name="lead_confirm"),
    path("leads/<int:lead_id>/close/", lead_views.lead_close_lost, name="lead_close_lost"),
    path("leads/activity/<int:activity_id>/edit/", lead_views.activity_edit, name="activity_edit"),
    path("leads/activity/<int:activity_id>/delete/", lead_views.activity_delete, name="activity_delete"),
    path("users/", views.user_list, name="user_list"),
    path("users/add/", views.add_user, name="add_user"),
    path("users/add/", views.add_user, name="user_add"),
    path("users/<int:user_id>/edit/", views.edit_user, name="edit_user"),
    path("users/<int:user_id>/edit/", views.edit_user, name="user_edit"),
    path("users/<int:user_id>/assign-role/", views.assign_user_role, name="assign_user_role"),
    path("users/<int:user_id>/delete/", views.delete_user, name="delete_user"),
    path("users/<int:user_id>/delete/", views.delete_user, name="user_delete"),
    path("activity-log/", views.activity_log, name="activity_log"),
]
