# Generated by Django 4.2.27 on 2026-04-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="users",
            options={},
        ),
        migrations.AlterModelTable(
            name="customer",
            table="customers",
        ),
        migrations.AlterModelTable(
            name="users",
            table="users",
        ),
    ]
