# Generated by Django 4.2.27 on 2026-04-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customer_email_customer_name_customer_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("customer", "Customer"),
                    ("manager", "Manager"),
                    ("executive", "Executive"),
                    ("telecaller", "Telecaller"),
                ],
                default="customer",
                max_length=10,
            ),
        ),
    ]
