# Generated by Django 4.2.27 on 2026-04-28 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_users_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="id",
            new_name="u_id",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="id",
            new_name="cust_id",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="user",
            new_name="u_id",
        ),
        migrations.AlterField(
            model_name="users",
            name="u_id",
            field=models.AutoField(db_column="id", primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="customer",
            name="cust_id",
            field=models.AutoField(db_column="id", primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="customer",
            name="u_id",
            field=models.OneToOneField(db_column="u_id", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
