# Generated by Django 4.2.27 on 2026-04-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_customer_id_remove_customer_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="cust_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="users",
            name="u_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
