# Generated by Django 4.2.27 on 2026-04-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_customer_cust_id_alter_users_u_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="name",
            new_name="full_name",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="name",
            new_name="full_name",
        ),
        migrations.AlterField(
            model_name="customer",
            name="aadhar_number",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
