# Generated by Django 4.2.27 on 2026-05-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_rename_name_customer_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("customer", "Customer"),
                    ("manager", "Manager"),
                    ("executive", "Executive"),
                    ("telecaller", "Telecaller"),
                    ("accounts", "Accounts"),
                ],
                default="customer",
                max_length=10,
            ),
        ),
    ]
