# Generated by Django 6.0.4 on 2026-05-30 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_lead_leadactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('EDIT', 'Edited'), ('DELETE', 'Deleted'), ('CANCEL', 'Cancelled'), ('APPROVE', 'Approved'), ('STATUS', 'Status Changed')], max_length=20)),
                ('model_name', models.CharField(max_length=60)),
                ('object_id', models.CharField(blank=True, default='', max_length=60)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('changes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
