# Generated by Django 4.2.27 on 2026-06-25 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        ('accounts', '0018_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='saas.organization'),
        ),
    ]
