from django.urls import path

from . import views


urlpatterns = [
    path("booking/", views.booking_list, name="booking_list"),
    path("booking/add/", views.booking_create, name="booking_add"),
    path("booking/<int:b_id>/", views.booking_view, name="booking_view"),
    path("booking/<int:b_id>/edit/", views.booking_edit, name="booking_edit"),
    path("booking/<int:b_id>/kgp/", views.booking_mark_kgp, name="booking_mark_kgp"),
    path("booking/<int:b_id>/kgp/edit/", views.booking_kgp_edit, name="booking_kgp_edit"),
    path("booking/<int:b_id>/kgp/swap/", views.booking_kgp_swap, name="booking_kgp_swap"),
    path("booking/<int:b_id>/cancel/", views.booking_cancel, name="booking_cancel"),
    path("booking/<int:b_id>/delete/", views.booking_delete, name="booking_delete"),
    path("booking/<int:b_id>/download/", views.booking_download, name="booking_download"),
    path("booking/<int:b_id>/client-copy/", views.booking_client_copy, name="booking_client_copy"),
    path("booking/<int:b_id>/share-email/", views.booking_share_email, name="booking_share_email"),

    path("api/customer-by-phone/", views.customer_by_phone, name="customer_by_phone"),
    path("api/agent-details/", views.agent_details, name="agent_details"),
    
    path("projects/", views.project_list, name="project_list"),
    path("projects/add/", views.project_add, name="project_add"),
    path("projects/<int:p_id>/edit/", views.project_edit, name="project_edit"),
    path("projects/<int:p_id>/delete/", views.project_delete, name="project_delete"),
    path("store-settings/booking-agents/", views.booking_agent_settings, name="booking_agent_settings"),
    path("master-plots/", views.master_plots, name="master_plots"),
    
    path("agents/<str:role>/", views.agent_list, name="agent_list"),
    path("agents/<str:role>/add/", views.agent_add, name="agent_add"),
    path(
        "agents/accounts/<int:am_id>/transactions/",
        views.accounts_transactions,
        name="accounts_transactions",
    ),
    path("agents/accounts/payment/<int:adp_id>/edit/", views.accounts_payment_edit, name="accounts_payment_edit"),
    path("agents/accounts/payment/<int:adp_id>/delete/", views.accounts_payment_delete, name="accounts_payment_delete"),
    path("agents/<int:am_id>/edit/", views.agent_edit, name="agent_edit"),
    path("agents/<int:am_id>/delete/", views.agent_delete, name="agent_delete"),

    path("receipts/", views.receipt_list, name="receipt_list"),
    path("receipts/add/", views.receipt_add, name="receipt_add"),
    path("receipts/<int:rm_id>/", views.receipt_view, name="receipt_view"),
    path("receipts/<int:rm_id>/share-email/", views.receipt_share_email, name="receipt_share_email"),
    path("receipts/<int:rm_id>/edit/", views.receipt_edit, name="receipt_edit"),
    path("receipts/<int:rm_id>/delete/", views.receipt_delete, name="receipt_delete"),
    path("payments/", views.payment_list, name="payment_list"),
    path("payments/add/", views.payment_request, name="payment_add"),
    path("payments/<int:p_id>/approve/", views.payment_approve, name="payment_approve"),
    path("ledger/", views.ledger_list, name="ledger_list"),
    path("ledger/<int:b_id>/print/", views.ledger_print, name="ledger_print"),
    path("api/ledger-data/", views.ledger_data_api, name="ledger_data_api"),
    path("api/booking-details/", views.booking_details_api, name="booking_details_api"),
    path("api/bookings-by-phone/", views.bookings_by_phone, name="bookings_by_phone"),
    path("api/check-plot-availability/", views.check_plot_availability, name="check_plot_availability"),
    path("follow-up/", views.follow_up_report, name="follow_up_report"),
    path("percentage-follow-up/", views.percentage_follow_up, name="percentage_follow_up"),
    path("advance-follow-up/", views.advance_follow_up, name="advance_follow_up"),
    path("all-reports/", views.all_reports_dashboard, name="all_reports"),
    path("reports/customer-wise/", views.customer_wise_report, name="customer_wise_report"),
    path("reports/project-wise/", views.project_wise_report, name="project_wise_report"),
    path("reports/all-project/", views.all_project_report, name="all_project_report"),
    path("reports/team/", views.team_report, name="team_report"),
    path("reports/agent/<str:role>/", views.agent_report, name="agent_report"),
    path("api/agent-info/", views.get_agent_info, name="get_agent_info"),
    path("api/agent-withdrawal-data/", views.agent_withdrawal_data, name="agent_withdrawal_data"),
    path("my-payments/", views.my_payments, name="my_payments"),
    path("cancelled-plots/", views.cancelled_plots_list, name="cancelled_plots_list"),
    path("cancelled-plots/<int:cp_id>/refund/", views.update_refund_status, name="update_refund_status"),
    path("cancelled-plots/<int:cp_id>/delete/", views.cancelled_plot_delete, name="cancelled_plot_delete"),
    path("incentive-withdrawal/", views.incentive_withdrawal, name="incentive_withdrawal"),
]
