# Generated by Django 4.2.27 on 2026-06-25 11:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('subscription_started_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_ends_at', models.DateTimeField(blank=True, null=True)),
                ('razorpay_customer_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saas_organization',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('diamond', 'Diamond')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('price_inr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('billing_period_days', models.PositiveIntegerField(default=30)),
                ('max_projects', models.PositiveIntegerField(default=2, help_text='0 = unlimited')),
                ('max_users', models.PositiveIntegerField(default=5, help_text='0 = unlimited')),
                ('max_bookings', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('feature_leads', models.BooleanField(default=False)),
                ('feature_reports', models.BooleanField(default=False)),
                ('feature_agents', models.BooleanField(default=False)),
                ('feature_tally', models.BooleanField(default=False)),
                ('feature_api', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'saas_subscription_plan',
                'ordering': ['sort_order', 'price_inr'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired')], default='created', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, default='', max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, default='', max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, default='', max_length=255)),
                ('is_demo', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='saas.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='saas.subscriptionplan')),
            ],
            options={
                'db_table': 'saas_payment_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='saas.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('membership_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='saas.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saas_organization_membership',
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
