# Generated by Django 4.2.27 on 2026-04-28 05:20

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentMaster",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_name", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("executive", "Executive"),
                            ("telecaller", "Telecaller"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=7
                    ),
                ),
                (
                    "security_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("location", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="BookingMaster",
            fields=[
                ("booking_id", models.AutoField(primary_key=True, serialize=False)),
                ("booking_date", models.DateField()),
                ("phone", models.CharField(max_length=10)),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("occupation", models.CharField(blank=True, max_length=200)),
                ("present_address", models.TextField(blank=True)),
                ("permanent_address", models.TextField(blank=True)),
                ("aadhar_number", models.CharField(blank=True, max_length=20)),
                ("pin_code", models.CharField(blank=True, max_length=10)),
                (
                    "manager_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=7
                    ),
                ),
                (
                    "executive_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=7
                    ),
                ),
                (
                    "telecaller_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=7
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("upi", "UPI"),
                            ("bank", "Bank Transfer"),
                            ("cheque", "Cheque"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("payment_details", models.TextField(blank=True)),
                ("nominee", models.CharField(blank=True, max_length=200)),
                ("relationship", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("next_payment_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "apartment_layout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="bookings.project",
                    ),
                ),
                (
                    "executive",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "executive"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executive_bookings",
                        to="bookings.agentmaster",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "manager"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_bookings",
                        to="bookings.agentmaster",
                    ),
                ),
                (
                    "telecaller",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "telecaller"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telecaller_bookings",
                        to="bookings.agentmaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plot_number", models.CharField(blank=True, max_length=50)),
                ("plot_name", models.CharField(blank=True, max_length=200)),
                (
                    "area_sqft",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "booking_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="bookings.bookingmaster",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_items",
                        to="bookings.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BalanceMaster",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plot_number", models.CharField(blank=True, max_length=50)),
                ("plot_name", models.CharField(blank=True, max_length=200)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "balance_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance",
                        to="bookings.bookingmaster",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agentmaster",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bookings.project",
            ),
        ),
    ]
