# Generated by Django 4.2.27 on 2026-04-28 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="agentmaster",
            table="agent_master",
        ),
        migrations.AlterModelTable(
            name="balancemaster",
            table="balance_master",
        ),
        migrations.AlterModelTable(
            name="bookingitem",
            table="booking_item",
        ),
        migrations.AlterModelTable(
            name="bookingmaster",
            table="booking_master",
        ),
        migrations.AlterModelTable(
            name="project",
            table="project",
        ),
    ]
