# Generated by Django 4.2.27 on 2026-04-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_agentmaster_table_alter_balancemaster_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="num_plots",
            field=models.IntegerField(default=0),
        ),
    ]
