# Generated by Django 4.2.27 on 2026-04-28 09:23

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0003_project_num_plots"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agentmaster",
            old_name="percentage",
            new_name="commission_percentage",
        ),
        migrations.AddField(
            model_name="agentmaster",
            name="tds_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="agentmaster",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="agentmaster",
            unique_together={("user", "role")},
        ),
        migrations.RemoveField(
            model_name="agentmaster",
            name="agent_name",
        ),
        migrations.RemoveField(
            model_name="agentmaster",
            name="project",
        ),
    ]
