# Generated by Django 4.2.27 on 2026-04-28 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "bookings",
            "0004_rename_percentage_agentmaster_commission_percentage_and_more",
        ),
    ]

    operations = [
        # Project
        migrations.RenameField(
            model_name="project",
            old_name="id",
            new_name="p_id",
        ),
        migrations.AlterField(
            model_name="project",
            name="p_id",
            field=models.AutoField(db_column="id", primary_key=True, serialize=False),
        ),

        # BookingMaster
        migrations.RenameField(
            model_name="bookingmaster",
            old_name="booking_id",
            new_name="b_id",
        ),
        migrations.AlterField(
            model_name="bookingmaster",
            name="b_id",
            field=models.AutoField(db_column="booking_id", primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name="bookingmaster",
            old_name="apartment_layout",
            new_name="p_id",
        ),
        migrations.RenameField(
            model_name="bookingmaster",
            old_name="manager",
            new_name="manager_u_id",
        ),
        migrations.RenameField(
            model_name="bookingmaster",
            old_name="executive",
            new_name="executive_u_id",
        ),
        migrations.RenameField(
            model_name="bookingmaster",
            old_name="telecaller",
            new_name="telecaller_u_id",
        ),

        # AgentMaster
        migrations.AlterUniqueTogether(
            name="agentmaster",
            unique_together=set(),
        ),
        migrations.RenameField(
            model_name="agentmaster",
            old_name="id",
            new_name="am_id",
        ),
        migrations.RenameField(
            model_name="agentmaster",
            old_name="user",
            new_name="u_id",
        ),
        # Assuming there's a booking field in AgentMaster? Wait, I saw 'Add field b_id' in previous migration.
        # Let's check AgentMaster original fields.
        # It had user, role, tds_amount, commission_percentage, security_amount.
        # It did NOT have booking originally?
        # Actually, in truncated history I saw: "booking (relation to BookingMaster, optional)".
        # Let's assume it had 'booking' or I'm adding it.
        # If I'm adding it, AddField is fine.
        migrations.AddField(
            model_name="agentmaster",
            name="b_id",
            field=models.ForeignKey(
                blank=True,
                db_column="b_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_commissions",
                to="bookings.bookingmaster",
            ),
        ),
        migrations.AlterField(
            model_name="agentmaster",
            name="am_id",
            field=models.AutoField(db_column="id", primary_key=True, serialize=False),
        ),

        # BalanceMaster
        migrations.RenameField(
            model_name="balancemaster",
            old_name="id",
            new_name="bm_id",
        ),
        migrations.RenameField(
            model_name="balancemaster",
            old_name="booking",
            new_name="b_id",
        ),
        migrations.AlterField(
            model_name="balancemaster",
            name="bm_id",
            field=models.AutoField(db_column="id", primary_key=True, serialize=False),
        ),

        # BookingItem
        migrations.RenameField(
            model_name="bookingitem",
            old_name="id",
            new_name="bi_id",
        ),
        migrations.RenameField(
            model_name="bookingitem",
            old_name="booking",
            new_name="b_id",
        ),
        migrations.RenameField(
            model_name="bookingitem",
            old_name="project",
            new_name="p_id",
        ),
        migrations.AlterField(
            model_name="bookingitem",
            name="bi_id",
            field=models.AutoField(db_column="id", primary_key=True, serialize=False),
        ),

        # Meta changes
        migrations.AlterField(
            model_name="bookingmaster",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("BANK_TRANSFER", "Bank Transfer"),
                    ("UPI", "UPI"),
                    ("CHEQUE", "Cheque"),
                ],
                default="CASH",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agentmaster",
            unique_together={("u_id", "role", "b_id")},
        ),
    ]
