# Generated by Django 4.2.27 on 2026-04-28 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0005_alter_bookingmaster_booking_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentmaster",
            name="u_id",
            field=models.ForeignKey(
                db_column="u_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="balancemaster",
            name="b_id",
            field=models.OneToOneField(
                db_column="b_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balance",
                to="bookings.bookingmaster",
            ),
        ),
        migrations.AlterField(
            model_name="bookingitem",
            name="b_id",
            field=models.ForeignKey(
                db_column="b_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="bookings.bookingmaster",
            ),
        ),
        migrations.AlterField(
            model_name="bookingitem",
            name="p_id",
            field=models.ForeignKey(
                blank=True,
                db_column="p_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_items",
                to="bookings.project",
            ),
        ),
        migrations.AlterField(
            model_name="bookingmaster",
            name="executive_u_id",
            field=models.ForeignKey(
                blank=True,
                db_column="executive_u_id",
                limit_choices_to={"role": "executive"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executive_bookings",
                to="bookings.agentmaster",
            ),
        ),
        migrations.AlterField(
            model_name="bookingmaster",
            name="manager_u_id",
            field=models.ForeignKey(
                blank=True,
                db_column="manager_u_id",
                limit_choices_to={"role": "manager"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_bookings",
                to="bookings.agentmaster",
            ),
        ),
        migrations.AlterField(
            model_name="bookingmaster",
            name="p_id",
            field=models.ForeignKey(
                blank=True,
                db_column="p_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="bookings.project",
            ),
        ),
        migrations.AlterField(
            model_name="bookingmaster",
            name="telecaller_u_id",
            field=models.ForeignKey(
                blank=True,
                db_column="telecaller_u_id",
                limit_choices_to={"role": "telecaller"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="telecaller_bookings",
                to="bookings.agentmaster",
            ),
        ),
    ]
