# Generated by Django 4.2.27 on 2026-04-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_alter_agentmaster_u_id_alter_balancemaster_b_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentmaster",
            name="am_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="balancemaster",
            name="bm_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="bookingitem",
            name="bi_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="bookingmaster",
            name="b_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="p_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
