# Generated by Django 4.2.27 on 2026-04-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_alter_agentmaster_am_id_alter_balancemaster_bm_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancemaster",
            name="project_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
