# Generated by Django 4.2.27 on 2026-04-29 07:42

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0008_balancemaster_project_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="agentmaster",
            unique_together={("u_id", "role")},
        ),
        migrations.AlterField(
            model_name="agentmaster",
            name="commission_percentage",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="agentmaster",
            name="security_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="agentmaster",
            name="tds_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="bookingitem",
            name="area_sqft",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="bookingitem",
            name="booking_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="bookingitem",
            name="rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="bookingmaster",
            name="aadhar_number",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name="bookingmaster",
            name="email",
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="bookingmaster",
            name="executive_percentage",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="bookingmaster",
            name="executive_u_id",
            field=models.ForeignKey(
                blank=True,
                db_column="executive_u_id",
                limit_choices_to={"role": "executive"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executive_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bookingmaster",
            name="manager_percentage",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="bookingmaster",
            name="manager_u_id",
            field=models.ForeignKey(
                blank=True,
                db_column="manager_u_id",
                limit_choices_to={"role": "manager"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bookingmaster",
            name="phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="bookingmaster",
            name="telecaller_percentage",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="bookingmaster",
            name="telecaller_u_id",
            field=models.ForeignKey(
                blank=True,
                db_column="telecaller_u_id",
                limit_choices_to={"role": "telecaller"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="telecaller_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="agentmaster",
            name="b_id",
        ),
    ]
