# Generated by Django 4.2.27 on 2026-04-29 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0009_alter_agentmaster_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingmaster",
            name="u_id",
            field=models.ForeignKey(
                blank=True,
                db_column="u_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
