# Generated by Django 4.2.27 on 2026-04-29 10:01

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_bookingmaster_u_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiptMaster",
            fields=[
                ("rm_id", models.AutoField(primary_key=True, serialize=False)),
                ("receipt_date", models.DateField()),
                ("receipt_no", models.CharField(max_length=50, unique=True)),
                ("customer_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=15)),
                ("plot_number", models.CharField(max_length=200)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "pay_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "balance_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("UPI", "UPI"),
                            ("CHEQUE", "Cheque"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                ("payment_details", models.TextField(blank=True)),
                ("next_payment_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "b_id",
                    models.ForeignKey(
                        db_column="b_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="bookings.bookingmaster",
                    ),
                ),
            ],
            options={
                "db_table": "receipt_master",
                "ordering": ["-created_at"],
            },
        ),
    ]
