# Generated by Django 4.2.27 on 2026-04-30 04:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0011_receiptmaster"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingmaster",
            name="executive_security_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="bookingmaster",
            name="executive_tds",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="bookingmaster",
            name="manager_security_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="bookingmaster",
            name="manager_tds",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="bookingmaster",
            name="telecaller_security_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="bookingmaster",
            name="telecaller_tds",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="receiptmaster",
            name="receipt_no",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
