# Generated by Django 4.2.27 on 2026-04-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0012_bookingmaster_executive_security_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingmaster",
            name="payment_status",
            field=models.CharField(
                choices=[("FULL", "Full Payment"), ("PARTIAL", "Partial Payment")],
                default="PARTIAL",
                max_length=10,
            ),
        ),
    ]
