# Generated by Django 4.2.27 on 2026-04-30 09:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0013_bookingmaster_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancemaster",
            name="booking_advance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
    ]
