# Generated by Django 4.2.27 on 2026-05-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0014_balancemaster_booking_advance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentmaster",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("executive", "Executive"),
                    ("telecaller", "Telecaller"),
                    ("accounts", "Accounts"),
                ],
                max_length=20,
            ),
        ),
    ]
