# Generated by Django 4.2.27 on 2026-05-02 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0016_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="amount",
            new_name="pay_amount",
        ),
        migrations.AddField(
            model_name="bookingmaster",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
