# Generated by Django 4.2.27 on 2026-05-06 06:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0017_rename_amount_payment_pay_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingmaster",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("CANCELLED", "Cancelled")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CancelledPlot",
            fields=[
                ("cp_id", models.AutoField(primary_key=True, serialize=False)),
                ("cancellation_date", models.DateField(auto_now_add=True)),
                ("reason", models.TextField()),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "refund_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARTIAL", "Partial Refund"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "refund_amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("refund_notes", models.TextField(blank=True)),
                (
                    "b_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancelled_details",
                        to="bookings.bookingmaster",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cancelled_plot",
            },
        ),
    ]
