# Generated by Django 4.2.27 on 2026-05-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0018_bookingmaster_status_cancelledplot"),
    ]

    operations = [
        migrations.AddField(
            model_name="cancelledplot",
            name="plot_number",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
