# Generated by Django 4.2.27 on 2026-05-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0019_cancelledplot_plot_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="cancelledplot",
            name="closure_status",
            field=models.CharField(
                choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                default="OPEN",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="cancelledplot",
            name="released_for_rebooking",
            field=models.BooleanField(default=False),
        ),
    ]
