# Generated by Django 6.0.4 on 2026-05-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_incentivewithdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentivewithdrawalrequest',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='withdrawal_proofs/'),
        ),
    ]
