# Generated by Django 6.0.4 on 2026-05-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_incentivewithdrawalrequest_proof_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmaster',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
