# Generated by Django 6.0.4 on 2026-05-21 10:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_agentmaster_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmaster',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
