# Generated by Django 6.0.4 on 2026-05-29 08:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0029_bookingagentsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmaster',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='bookingmaster',
            name='executive_percentage',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='bookingmaster',
            name='manager_percentage',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='bookingmaster',
            name='telecaller_percentage',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7),
        ),
    ]
