# Generated by Django 6.0.4 on 2026-05-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0030_commission_percentage_4_decimal_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingagentsettings',
            name='company_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bookingagentsettings',
            name='company_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='bookingagentsettings',
            name='company_name',
            field=models.CharField(blank=True, default='LANDLINK REAL ESTATE', max_length=200),
        ),
        migrations.AddField(
            model_name='bookingagentsettings',
            name='company_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
