# Generated by Django 4.2.27 on 2026-06-25 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        ('bookings', '0032_project_organization_alter_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingagentsettings',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_settings', to='saas.organization'),
        ),
        migrations.AddField(
            model_name='bookingmaster',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='saas.organization'),
        ),
    ]
