# Generated by Django 6.0.4 on 2026-05-21 10:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerMaster',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('group', models.CharField(choices=[('BANK_CASH', 'Bank / Cash'), ('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('CAPITAL', 'Capital')], max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('opening_balance_type', models.CharField(choices=[('Dr', 'Debit'), ('Cr', 'Credit')], default='Dr', max_length=2)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tally_ledger_master',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('voucher_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('voucher_type', models.CharField(choices=[('PAYMENT', 'Payment Voucher'), ('RECEIPT', 'Receipt Voucher'), ('JOURNAL', 'Journal Entry'), ('CONTRA', 'Contra')], max_length=20)),
                ('voucher_date', models.DateField()),
                ('narration', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tally_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tally_voucher',
                'ordering': ['-voucher_date', '-v_id'],
            },
        ),
        migrations.CreateModel(
            name='VoucherEntry',
            fields=[
                ('ve_id', models.AutoField(primary_key=True, serialize=False)),
                ('dr_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cr_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('ledger', models.ForeignKey(db_column='l_id', on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='tally.ledgermaster')),
                ('v_id', models.ForeignKey(db_column='v_id', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tally.voucher')),
            ],
            options={
                'db_table': 'tally_voucher_entry',
            },
        ),
    ]
