# Generated by Django 6.0.4 on 2026-05-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgermaster',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ledgermaster',
            name='group',
            field=models.CharField(choices=[('BANK_CASH', 'Bank / Cash'), ('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('CAPITAL', 'Capital'), ('STAFF', 'Staff Member')], max_length=20),
        ),
    ]
